/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfaz2algorimo;





import javax.swing.JPanel;

/**
 *
 * @author Manuel Cueto
 */
public class Gráfica extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Gráfica
     */
    public Gráfica() {
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lsprimo = new javax.swing.JLabel();
        lprimo = new javax.swing.JLabel();
        lsfibonacci = new javax.swing.JLabel();
        lfibonacci = new javax.swing.JLabel();
        lspotencia = new javax.swing.JLabel();
        lpotencia = new javax.swing.JLabel();
        lssumadig = new javax.swing.JLabel();
        lsumadig = new javax.swing.JLabel();
        lsfactorial = new javax.swing.JLabel();
        lfactorialN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        blimpiar = new javax.swing.JButton();
        bcalcular = new javax.swing.JButton();
        eM = new javax.swing.JTextField();
        lN = new javax.swing.JLabel();
        eN = new javax.swing.JTextField();
        lM = new javax.swing.JLabel();
        lerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));
        jPanel1.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lsprimo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lsprimo.setForeground(new java.awt.Color(51, 51, 51));
        lsprimo.setText("Primo:");
        jPanel1.add(lsprimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 92, -1));
        jPanel1.add(lprimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 170, 20));

        lsfibonacci.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lsfibonacci.setForeground(new java.awt.Color(0, 0, 0));
        lsfibonacci.setText("Secuencia fibonacci hasta el valor menor o igual al resultado de NxM:");
        jPanel1.add(lsfibonacci, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 535, 14));

        lfibonacci.setBackground(new java.awt.Color(255, 255, 255));
        lfibonacci.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lfibonacci.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lfibonacci, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 369, 20));

        lspotencia.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lspotencia.setForeground(new java.awt.Color(51, 51, 51));
        lspotencia.setText("Potencia de N elevado a la M:");
        jPanel1.add(lspotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        lpotencia.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lpotencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 179, -1));

        lssumadig.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lssumadig.setForeground(new java.awt.Color(51, 51, 51));
        lssumadig.setText("Suma de los dígitos del valor de N x M:");
        jPanel1.add(lssumadig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, 10));

        lsumadig.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lsumadig, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 156, -1));

        lsfactorial.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lsfactorial.setForeground(new java.awt.Color(51, 51, 51));
        lsfactorial.setText("Factorial de N:");
        jPanel1.add(lsfactorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        lfactorialN.setForeground(new java.awt.Color(0, 51, 51));
        jPanel1.add(lfactorialN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 242, 24));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        blimpiar.setText("Limpiar");
        blimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(blimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 90, -1));

        bcalcular.setText("Calcular");
        bcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcalcularActionPerformed(evt);
            }
        });
        jPanel2.add(bcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 90, -1));

        eM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMActionPerformed(evt);
            }
        });
        jPanel2.add(eM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 230, 30));

        lN.setForeground(new java.awt.Color(255, 255, 255));
        lN.setText("Ingrese número N del 1 al 99:");
        jPanel2.add(lN, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 20));

        eN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNActionPerformed(evt);
            }
        });
        jPanel2.add(eN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 230, 30));

        lM.setForeground(new java.awt.Color(255, 255, 255));
        lM.setText("Ingrese número M del 1 al 99:");
        jPanel2.add(lM, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 90));

        lerror.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lerror.setForeground(new java.awt.Color(0, 0, 0));
        lerror.setText("as");
        jPanel1.add(lerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcalcularActionPerformed
        String ene = eN.getText();
        String eme = eM.getText();
        int n = 0;
        int m = 0;
        try{
            n = Integer.parseInt(ene);
            
            
        }
        catch(Exception e){
            eN.setText("No ingresaste un número entero N");
        }
        try{
            m = Integer.parseInt(eme);
            
        }
        catch(Exception e){
            eM.setText("No ingresaste un número entero M");
        }
        if ((n >= 1 && n <= 99) && (m >= 1 && m <= 99) ){
            String texto = "";
            int cont = 0;
            String nm = Integer.toString(n*m);
            int longitud = nm.length();
            int sum = sumadig(nm, longitud-1);
            int factor = factorial(n);
            
            int potenci = potencia(n,m);
            boolean r = primo(m,m-1);
            if (r) lprimo.setText("Sí");
            else lprimo.setText("No");
            mostrar(factor,sum,potenci);
            
            while (n*m >= fibonacci(cont)){
                texto += fibonacci(cont) + " ";
                
                cont++;
            }
            lfibonacci.setText(texto);
            
                
        } else if ((n < 1 || n > 99) ||(m < 1 || m > 99) ){
         lerror.setText("No ingresaste un número entre 1 y 99");
        }
        
        
        /*fibonacci(n);*/
    }//GEN-LAST:event_bcalcularActionPerformed

    private void eNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNActionPerformed

    private void eMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMActionPerformed

    private void blimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_blimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gráfica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gráfica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcalcular;
    private javax.swing.JButton blimpiar;
    private javax.swing.JTextField eM;
    private javax.swing.JTextField eN;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lM;
    private javax.swing.JLabel lN;
    private javax.swing.JLabel lerror;
    private javax.swing.JLabel lfactorialN;
    private javax.swing.JLabel lfibonacci;
    private javax.swing.JLabel lpotencia;
    private javax.swing.JLabel lprimo;
    private javax.swing.JLabel lsfactorial;
    private javax.swing.JLabel lsfibonacci;
    private javax.swing.JLabel lspotencia;
    private javax.swing.JLabel lsprimo;
    private javax.swing.JLabel lssumadig;
    private javax.swing.JLabel lsumadig;
    // End of variables declaration//GEN-END:variables

    public void limpiar(){
        lprimo.setText("");
        lfibonacci.setText("");
        lsumadig.setText("");
        lpotencia.setText("");
        lfactorialN.setText("");
        eN.setText("");
        eM.setText("");
        lerror.setText("");
        
    }
    public int factorial(int numero){
        
        
        if (numero == 1){
            return 1;
        } else{
            return numero*factorial(numero-1);
        }
        
    }
    public void mostrar(int factorial,int suma,int poten){
        String rfactorial;
        String rsuma;
        String rpoten;
        rfactorial = Integer.toString(factorial);
        rsuma = Integer.toString(suma);
        rpoten = Integer.toString(poten);
        lfactorialN.setText(rfactorial);
        lsumadig.setText(rsuma);
        lpotencia.setText(rpoten);
        
    }
    public int sumadig(String nm, int longi){
        if(longi == 0){
            return Character.getNumericValue(nm.charAt(longi));
        }else{
            return  Character.getNumericValue(nm.charAt(longi)) + sumadig(nm,longi-1);
        }
        
    }
    
    public int fibonacci(int n){
       if (n == 0){
           return 0;
       }else if(n == 1 || n == 2) {
           return 1;
       }else{
           return (fibonacci(n-1)+fibonacci(n-2));
       }
    }
    
    public int potencia(int n,int m){
        if(m == 1){
            return n;
        }
        else{
            return n * potencia(n,m-1);
        }
    }
    public boolean primo(int m, int divi){
        if (m == 1){
            return true;
        }
        if(divi ==  1){
            return true;
        }else {
            if((int) m % divi == 0){
                return false;
            } else{
                return primo(m,divi-1);
            }
        }
        
    
    }
    
    
                    
        
        
    
}
